language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

script: go test -v

install:
  - go get -v

  before_deploy: make build-all
  deploy:
    provider: releases
    api_key:
      secure: f7c5581d37b4a267a1fba94e811499119385e97b
    file_glob: true
    file: bin/*
    skip_cleanup: true
    on:
      repo: JieTrancender/ci-test
      tags: true
